/**
 * 标签管理器
 * 对应 Java 版本的 kernel/geos/LabelManager.java
 */

import { GeoElementType } from './geos/GeoElement';

/**
 * 标签类型
 */
export type LabelType = 'point' | 'line' | 'segment' | 'ray' | 'circle' | 'polygon' | 'vector' | 'text' | 'number' | 'angle' | 'function' | 'boolean' | 'conic' | 'polyline';

/**
 * 标签模式
 */
export type LabelMode = 'automatic' | 'manual' | 'hidden';

/**
 * 标签信息
 */
export interface LabelInfo {
  label: string;
  type: LabelType;
  mode: LabelMode;
  elementId: string;
  isAutoGenerated: boolean;
}

/**
 * 标签管理器
 * 参考 Java 版本的 LabelManager
 * 管理几何元素的标签生成和冲突处理
 */
export class LabelManager {
  private labelToElement: Map<string, string> = new Map();
  private elementToLabel: Map<string, string> = new Map();
  private labelCounters: Map<LabelType, number> = new Map();
  private reservedLabels: Set<string> = new Set();
  private protectedLabels: Set<string> = new Set();

  /**
   * 生成标签
   * @param type 标签类型
   * @returns 生成的标签
   */
  generateLabel(type: LabelType): string {
    const counter = (this.labelCounters.get(type) || 0) + 1;
    this.labelCounters.set(type, counter);

    return this.generateLabelByType(type, counter);
  }

  /**
   * 根据类型和计数器生成标签
   * @param type 标签类型
   * @param counter 计数器
   * @returns 标签
   */
  private generateLabelByType(type: LabelType, counter: number): string {
    switch (type) {
      case 'point':
        return this.generatePointLabel(counter);
      case 'line':
      case 'segment':
      case 'ray':
        return this.generateLineLabel(counter);
      case 'circle':
        return this.generateCircleLabel(counter);
      case 'polygon':
        return `poly${counter}`;
      case 'vector':
        return `v${counter}`;
      case 'text':
        return `text${counter}`;
      case 'number':
        return `n${counter}`;
      case 'angle':
        return this.generateAngleLabel(counter);
      case 'function':
        return `f${counter}`;
      default:
        return `${type}${counter}`;
    }
  }

  /**
   * 生成点标签 (A, B, C, ..., Z, A1, B1, ...)
   * @param counter 计数器
   * @returns 点标签
   */
  private generatePointLabel(counter: number): string {
    if (counter <= 26) {
      return String.fromCharCode(64 + counter); // A, B, C, ...
    }
    const letter = String.fromCharCode(64 + ((counter - 1) % 26) + 1);
    const number = Math.floor((counter - 1) / 26);
    return `${letter}${number}`;
  }

  /**
   * 生成线标签 (a, b, c, ..., z, a1, b1, ...)
   * @param counter 计数器
   * @returns 线标签
   */
  private generateLineLabel(counter: number): string {
    if (counter <= 26) {
      return String.fromCharCode(96 + counter); // a, b, c, ...
    }
    const letter = String.fromCharCode(96 + ((counter - 1) % 26) + 1);
    const number = Math.floor((counter - 1) / 26);
    return `${letter}${number}`;
  }

  /**
   * 生成圆标签
   * @param counter 计数器
   * @returns 圆标签
   */
  private generateCircleLabel(counter: number): string {
    if (counter <= 26) {
      return String.fromCharCode(96 + counter); // c, d, e, ...
    }
    return `c${counter - 26 + 1}`;
  }

  /**
   * 生成角度标签
   * @param counter 计数器
   * @returns 角度标签
   */
  private generateAngleLabel(counter: number): string {
    const greekLetters = ['α', 'β', 'γ', 'δ', 'ε', 'ζ', 'η', 'θ', 'ι', 'κ', 'λ', 'μ', 'ν', 'ξ', 'ο', 'π', 'ρ', 'σ', 'τ', 'υ', 'φ', 'χ', 'ψ', 'ω'];
    if (counter <= greekLetters.length) {
      return greekLetters[counter - 1];
    }
    return `α${counter - greekLetters.length}`;
  }

  /**
   * 注册标签
   * @param label 标签
   * @param elementId 元素ID
   * @returns 是否成功
   */
  registerLabel(label: string, elementId: string): boolean {
    if (this.labelToElement.has(label)) {
      return false; // 标签已存在
    }

    this.labelToElement.set(label, elementId);
    this.elementToLabel.set(elementId, label);
    return true;
  }

  /**
   * 注销标签
   * @param label 标签
   */
  unregisterLabel(label: string): void {
    const elementId = this.labelToElement.get(label);
    if (elementId) {
      this.labelToElement.delete(label);
      this.elementToLabel.delete(elementId);
    }
  }

  /**
   * 通过元素ID注销标签
   * @param elementId 元素ID
   */
  unregisterByElementId(elementId: string): void {
    const label = this.elementToLabel.get(elementId);
    if (label) {
      this.labelToElement.delete(label);
      this.elementToLabel.delete(elementId);
    }
  }

  /**
   * 获取标签对应的元素ID
   * @param label 标签
   * @returns 元素ID或undefined
   */
  getElementId(label: string): string | undefined {
    return this.labelToElement.get(label);
  }

  /**
   * 获取元素ID对应的标签
   * @param elementId 元素ID
   * @returns 标签或undefined
   */
  getLabel(elementId: string): string | undefined {
    return this.elementToLabel.get(elementId);
  }

  /**
   * 检查标签是否存在
   * @param label 标签
   * @returns 是否存在
   */
  hasLabel(label: string): boolean {
    return this.labelToElement.has(label);
  }

  /**
   * 重命名标签
   * @param oldLabel 旧标签
   * @param newLabel 新标签
   * @returns 是否成功
   */
  renameLabel(oldLabel: string, newLabel: string): boolean {
    if (!this.labelToElement.has(oldLabel)) {
      return false;
    }
    if (this.labelToElement.has(newLabel)) {
      return false;
    }

    const elementId = this.labelToElement.get(oldLabel)!;
    this.labelToElement.delete(oldLabel);
    this.labelToElement.set(newLabel, elementId);
    this.elementToLabel.set(elementId, newLabel);
    return true;
  }

  /**
   * 保留标签
   * @param label 标签
   */
  reserveLabel(label: string): void {
    this.reservedLabels.add(label);
  }

  /**
   * 取消保留标签
   * @param label 标签
   */
  unreserveLabel(label: string): void {
    this.reservedLabels.delete(label);
  }

  /**
   * 检查标签是否被保留
   * @param label 标签
   * @returns 是否被保留
   */
  isReserved(label: string): boolean {
    return this.reservedLabels.has(label);
  }

  /**
   * 重置标签管理器
   * 清空所有计数器和映射
   */
  reset(): void {
    this.labelToElement.clear();
    this.elementToLabel.clear();
    this.labelCounters.clear();
    this.reservedLabels.clear();
    this.protectedLabels.clear();
  }

  /**
   * 保护标签（不可删除）
   * @param label 标签
   */
  protectLabel(label: string): void {
    this.protectedLabels.add(label);
  }

  /**
   * 取消保护标签
   * @param label 标签
   */
  unprotectLabel(label: string): void {
    this.protectedLabels.delete(label);
  }

  /**
   * 检查标签是否被保护
   * @param label 标签
   * @returns 是否被保护
   */
  isLabelProtected(label: string): boolean {
    return this.protectedLabels.has(label);
  }

  /**
   * 检查标签是否被保留
   * @param label 标签
   * @returns 是否被保留
   */
  isLabelReserved(label: string): boolean {
    return this.reservedLabels.has(label);
  }

  /**
   * 获取下一个可用标签
   * @param type 标签类型
   * @returns 可用标签
   */
  getNextAvailableLabel(type: LabelType): string {
    let label: string;
    let attempts = 0;
    const maxAttempts = 1000;

    do {
      label = this.generateLabel(type);
      attempts++;
    } while ((this.hasLabel(label) || this.isLabelReserved(label)) && attempts < maxAttempts);

    return label;
  }

  /**
   * 解析标签类型
   * @param label 标签
   * @returns 标签类型或undefined
   */
  parseLabelType(label: string): LabelType | undefined {
    if (/^[A-Z]\d*$/.test(label)) return 'point';
    if (/^[a-z]\d*$/.test(label)) return 'line';
    if (/^s\d+$/.test(label)) return 'segment';
    if (/^r\d+$/.test(label)) return 'ray';
    if (/^c\d*$/.test(label)) return 'circle';
    if (/^poly\d+$/.test(label)) return 'polygon';
    if (/^v\d+$/.test(label)) return 'vector';
    if (/^text\d+$/.test(label)) return 'text';
    if (/^n\d+$/.test(label)) return 'number';
    if (/^[αβγδεζηθικλμνξοπρστυφχψω]/.test(label)) return 'angle';
    if (/^f\d+$/.test(label)) return 'function';
    return undefined;
  }

  /**
   * 获取所有标签
   * @returns 标签数组
   */
  getAllLabels(): string[] {
    return Array.from(this.labelToElement.keys());
  }

  /**
   * 获取指定类型的所有标签
   * @param type 标签类型
   * @returns 标签数组
   */
  getLabelsByType(type: LabelType): string[] {
    return this.getAllLabels().filter(label => this.parseLabelType(label) === type);
  }

  /**
   * 清空所有标签
   */
  clear(): void {
    this.labelToElement.clear();
    this.elementToLabel.clear();
    this.labelCounters.clear();
    this.reservedLabels.clear();
    this.protectedLabels.clear();
  }

  /**
   * 重置计数器
   */
  resetCounters(): void {
    this.labelCounters.clear();
  }

  /**
   * 导出标签映射
   * @returns 标签映射对象
   */
  export(): Record<string, string> {
    const result: Record<string, string> = {};
    for (const [label, elementId] of this.labelToElement) {
      result[label] = elementId;
    }
    return result;
  }

  /**
   * 导入标签映射
   * @param data 标签映射对象
   */
  import(data: Record<string, string>): void {
    for (const [label, elementId] of Object.entries(data)) {
      this.registerLabel(label, elementId);
    }
  }
}

/**
 * 将 GeoElementType 转换为 LabelType
 * @param geoType 几何元素类型
 * @returns 标签类型
 */
export function geoTypeToLabelType(geoType: GeoElementType): LabelType {
  const mapping: Partial<Record<GeoElementType, LabelType>> = {
    point: 'point',
    line: 'line',
    segment: 'segment',
    ray: 'ray',
    circle: 'circle',
    polygon: 'polygon',
    vector: 'vector',
    text: 'text',
    boolean: 'boolean',
    function: 'function',
    conic: 'conic',
    polyline: 'polyline',
    angle: 'angle',
    numeric: 'number',
  };
  return mapping[geoType] || 'point';
}

